# Generated by Django 4.2.14 on 2024-07-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_index_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
